### ISSUE TITLE
Question about the `sila` function implementation

### ISSUE THREAD

**Issue by KGZaker** [bilgelm/silaR#2]
Thank you so much for implementing the SILA functionality in R. It has been incredibly helpful for my work. However, I got a few questions regarding the `sila` function :

- In the MATLAB version, it appears that subjects with only one evaluation are excluded first (`t = t(t.ns>1,:); % remove cases without longitudinal data`), and then the modeling is performed (`ILLA(t.age,t.val,t.subid,dt,val0,maxi,sk(i))`). Therefore, in the R version, should the line `illa_res <- illa(df, dt, val0, maxi, sk[i])` be modified to `illa_res <- illa(t, dt, val0, maxi, sk[i])`? This way, subjects with only a single evaluation are excluded before modeling.
- Additionally, I would like to confirm: for example, if my sample IDs are sub-1 sub-2 sub-2 sub-3 sub-3, does SILA model constructed only based on sub-2 sub-2 sub-3 sub-3? And if so, can I still use `SILA_estimate()` to predict the age of onset for sub-1?

I would greatly appreciate your clarification on these points.

**Comment by bilgelm** [comment]
Hi @KGZaker,

Great to hear that you're finding the R implementation helpful!

1. Changing `df` to `t` in https://github.com/bilgelm/silaR/blob/7f0d09fa8ab8ebd4e1bba3dce90197be5e387429/R/sila.R#L76 wouldn't make a difference since subjects with a single visit are excluded in `illa`: https://github.com/bilgelm/silaR/blob/7f0d09fa8ab8ebd4e1bba3dce90197be5e387429/R/illa.R#L54

2. Yes. Model fitting uses subjects with at least two visits, but estimation is done using all subjects (including those with a single visit).
